// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// Cell glyphs.
const (
	glyphFull    = "✓"
	glyphPartial = "~"
)

// render produces the full Markdown matrix document.
func (m *matrix) render() string {
	var b strings.Builder
	b.WriteString("<!-- Generated by hack/provider-compatibility-matrix. DO NOT EDIT. Run `make docs`. -->\n")
	b.WriteString("# Vendor compatibility matrix\n\n")
	b.WriteString("Generated by scanning provider code for `apistatus.NewUnsupportedFieldError()` calls.\n\n")
	b.WriteString("Full support (✓) means no such call was found. Providers that reject a field with a plain error, or whose `EnsureX` is an intentional no-op, are indistinguishable from full support.\n\n")
	fmt.Fprintf(&b, "- %s full  &nbsp; %s partial  &nbsp\n\n",
		glyphFull, glyphPartial)

	// Header
	b.WriteString("| Resource |")
	for _, col := range m.columns {
		fmt.Fprintf(&b, " %s |", col.name)
	}
	b.WriteString("\n|---|")
	for range m.columns {
		b.WriteString("---|")
	}
	b.WriteString("\n")

	// Notes, each reachable from its cell glyph via an explicit anchor. Collected
	// per provider so the Notes section can group them under the provider heading.
	type note struct {
		anchor string
		kind   string
		fields []string
	}
	notesByColumn := make(map[string][]note)

	// Resource names link into the API reference when a matching heading exists.
	anchors := apiRefAnchors(apiRefPath)

	for _, kind := range m.kinds {
		b.WriteString("| ")
		b.WriteString(resourceCell(kind, anchors))
		b.WriteString(" |")
		for _, col := range m.columns {
			c := m.support[kind][col.name]
			glyph := renderGlyph(c)
			if c.implemented && len(c.unsupportedFields) > 0 {
				anchor := noteAnchor(kind, col.name)
				notesByColumn[col.name] = append(notesByColumn[col.name],
					note{anchor: anchor, kind: kind, fields: c.unsupportedFields})
				glyph = fmt.Sprintf("[%s](#%s)", glyph, anchor)
			}
			b.WriteString(" ")
			b.WriteString(glyph)
			b.WriteString(" |")
		}
		b.WriteString("\n")
	}

	hasNotes := false
	for _, col := range m.columns {
		if len(notesByColumn[col.name]) > 0 {
			hasNotes = true
			break
		}
	}
	if hasNotes {
		b.WriteString("\n## List of resources with incomplete support\n\n")
		for _, col := range m.columns {
			ns := notesByColumn[col.name]
			if len(ns) == 0 {
				continue
			}
			fmt.Fprintf(&b, "### %s\n\n", col.name)
			for _, n := range ns {
				fmt.Fprintf(&b, "<a id=\"%s\"></a>\n**%s**\n\n", n.anchor, n.kind)
				for _, f := range n.fields {
					fmt.Fprintf(&b, "- `%s`\n", f)
				}
				b.WriteString("\n")
			}
		}
	}
	return b.String()
}

// noteAnchor returns the anchor id linking a partial cell to its note.
func noteAnchor(kind, colName string) string {
	return "note-" + slug(kind) + "-" + slug(colName)
}

// slug lowercases s and collapses runs of non-[a-z0-9] characters to a dash.
func slug(s string) string {
	var b strings.Builder
	dash := false
	for _, r := range strings.ToLower(s) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			dash = false
			continue
		}
		if !dash && b.Len() > 0 {
			b.WriteByte('-')
			dash = true
		}
	}
	return strings.TrimRight(b.String(), "-")
}

// apiRefAnchors returns the lowercased H4 heading names from the API reference.
// A missing file yields nil, so the matrix still generates without resource links.
func apiRefAnchors(path string) map[string]bool {
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()
	anchors := make(map[string]bool)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if name, ok := strings.CutPrefix(line, "#### "); ok {
			anchors[strings.ToLower(strings.TrimSpace(name))] = true
		}
	}
	return anchors
}

// resourceCell renders a kind as an API reference link, or plain text if no
// matching anchor exists. kindToAnchor overrides take precedence.
func resourceCell(kind string, anchors map[string]bool) string {
	anchor := strings.ToLower(kind)
	if override, ok := kindToAnchor[kind]; ok {
		anchor = override
	}
	if anchors[anchor] {
		return fmt.Sprintf("[%s](/api-reference/#%s)", kind, anchor)
	}
	return kind
}

// renderGlyph returns the cell glyph: full, partial, or empty when unimplemented.
func renderGlyph(c cell) string {
	switch {
	case !c.implemented:
		return ""
	case len(c.unsupportedFields) == 0:
		return glyphFull
	default:
		return glyphPartial
	}
}
