// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate-resources; DO NOT EDIT.

package cmd

type ResourceDef struct {
	Name    string
	Aliases []string
	Kind    string
	Group   string
	Version string
}

var resourceDefs = []ResourceDef{
	{Name: "aaa", Aliases: []string{}, Kind: "AAA", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "aaaconfigs", Aliases: []string{"aaaconfig", "nxaaa"}, Kind: "AAAConfig", Group: "nx.cisco.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "accesscontrollists", Aliases: []string{"accesscontrollist", "acl"}, Kind: "AccessControlList", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "banners", Aliases: []string{"banner"}, Kind: "Banner", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "bgp", Aliases: []string{}, Kind: "BGP", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "bgpconfigs", Aliases: []string{"bgpconfig", "nxbgp"}, Kind: "BGPConfig", Group: "nx.cisco.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "bgppeers", Aliases: []string{"bgppeer", "peer", "bgpneighbor"}, Kind: "BGPPeer", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "bordergateways", Aliases: []string{"bordergateway", "bgw"}, Kind: "BorderGateway", Group: "nx.cisco.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "certificates", Aliases: []string{"certificate", "cert", "netcert"}, Kind: "Certificate", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "claims", Aliases: []string{"claim"}, Kind: "Claim", Group: "pool.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "configbackups", Aliases: []string{"configbackup"}, Kind: "ConfigBackup", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "devices", Aliases: []string{"device", "dev"}, Kind: "Device", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "dhcprelays", Aliases: []string{"dhcprelay"}, Kind: "DHCPRelay", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "dns", Aliases: []string{}, Kind: "DNS", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "ethernetsegments", Aliases: []string{"ethernetsegment", "es"}, Kind: "EthernetSegment", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "evpninstances", Aliases: []string{"evpninstance", "evi", "vni"}, Kind: "EVPNInstance", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "fabrics", Aliases: []string{"fabric"}, Kind: "Fabric", Group: "evpn.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "indexpools", Aliases: []string{"indexpool", "idxpool"}, Kind: "IndexPool", Group: "pool.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "indices,singular=index,shortName=idx", Aliases: []string{}, Kind: "Index", Group: "pool.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "interfaceconfigs", Aliases: []string{"interfaceconfig", "nxint"}, Kind: "InterfaceConfig", Group: "nx.cisco.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "interfaces", Aliases: []string{"interface", "int"}, Kind: "Interface", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "ipaddresses,singular=ipaddress,shortName=ipa", Aliases: []string{}, Kind: "IPAddress", Group: "pool.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "ipaddresspools", Aliases: []string{"ipaddresspool", "ippool"}, Kind: "IPAddressPool", Group: "pool.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "ipprefixes,singular=ipprefix,shortName=pfx", Aliases: []string{}, Kind: "IPPrefix", Group: "pool.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "ipprefixpools", Aliases: []string{"ipprefixpool", "pfxpool"}, Kind: "IPPrefixPool", Group: "pool.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "isis", Aliases: []string{}, Kind: "ISIS", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "lldpconfigs", Aliases: []string{"lldpconfig"}, Kind: "LLDPConfig", Group: "nx.cisco.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "lldps", Aliases: []string{"lldp"}, Kind: "LLDP", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "managementaccessconfigs", Aliases: []string{"managementaccessconfig", "nxmgmt", "nxmgmtaccess"}, Kind: "ManagementAccessConfig", Group: "nx.cisco.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "managementaccesses", Aliases: []string{"managementaccess", "mgmt", "mgmtaccess"}, Kind: "ManagementAccess", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "networkvirtualizationedgeconfigs", Aliases: []string{"networkvirtualizationedgeconfig", "nveconfig"}, Kind: "NetworkVirtualizationEdgeConfig", Group: "nx.cisco.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "networkvirtualizationedges", Aliases: []string{"networkvirtualizationedge", "nve", "vtep"}, Kind: "NetworkVirtualizationEdge", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "ntp", Aliases: []string{}, Kind: "NTP", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "ospf", Aliases: []string{}, Kind: "OSPF", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "pim", Aliases: []string{}, Kind: "PIM", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "prefixsets", Aliases: []string{"prefixset"}, Kind: "PrefixSet", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "routingpolicies", Aliases: []string{"routingpolicy", "routemap"}, Kind: "RoutingPolicy", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "snmp", Aliases: []string{}, Kind: "SNMP", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "syslogs", Aliases: []string{"syslog"}, Kind: "Syslog", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "systems", Aliases: []string{"system", "nxsystem"}, Kind: "System", Group: "nx.cisco.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "users", Aliases: []string{"user"}, Kind: "User", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "vlans", Aliases: []string{"vlan"}, Kind: "VLAN", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "vpcdomains", Aliases: []string{"vpcdomain", "vpcdomain"}, Kind: "VPCDomain", Group: "nx.cisco.networking.metal.ironcore.dev", Version: "v1alpha1"},
	{Name: "vrfs", Aliases: []string{"vrf"}, Kind: "VRF", Group: "networking.metal.ironcore.dev", Version: "v1alpha1"},
}

// QualifiedName returns the resource name in "name.group" form understood by
// the Kubernetes resource builder, pinning the lookup to this resource's API
// group and avoiding clashes with same-named types from other controllers
// (e.g. Calico BGPPeer, cert-manager Certificate).
func (r ResourceDef) QualifiedName() string {
	if r.Group == "" {
		return r.Name
	}
	return r.Name + "." + r.Group
}
