//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/ironcore-dev/network-operator/api/core/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnycastRendezvousPoint) DeepCopyInto(out *AnycastRendezvousPoint) {
	*out = *in
	if in.MulticastGroups != nil {
		in, out := &in.MulticastGroups, &out.MulticastGroups
		*out = make([]corev1alpha1.IPPrefix, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.DeviceSelector.DeepCopyInto(&out.DeviceSelector)
	in.ClientDeviceSelector.DeepCopyInto(&out.ClientDeviceSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnycastRendezvousPoint.
func (in *AnycastRendezvousPoint) DeepCopy() *AnycastRendezvousPoint {
	if in == nil {
		return nil
	}
	out := new(AnycastRendezvousPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Fabric) DeepCopyInto(out *Fabric) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Fabric.
func (in *Fabric) DeepCopy() *Fabric {
	if in == nil {
		return nil
	}
	out := new(Fabric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Fabric) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAnycastGatewaySpec) DeepCopyInto(out *FabricAnycastGatewaySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAnycastGatewaySpec.
func (in *FabricAnycastGatewaySpec) DeepCopy() *FabricAnycastGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(FabricAnycastGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricBUMSpec) DeepCopyInto(out *FabricBUMSpec) {
	*out = *in
	if in.PIM != nil {
		in, out := &in.PIM, &out.PIM
		*out = new(FabricPIMSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricBUMSpec.
func (in *FabricBUMSpec) DeepCopy() *FabricBUMSpec {
	if in == nil {
		return nil
	}
	out := new(FabricBUMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricIBGPSpec) DeepCopyInto(out *FabricIBGPSpec) {
	*out = *in
	out.ASNumber = in.ASNumber
	if in.RouteReflectors != nil {
		in, out := &in.RouteReflectors, &out.RouteReflectors
		*out = make([]RouteReflectorGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricIBGPSpec.
func (in *FabricIBGPSpec) DeepCopy() *FabricIBGPSpec {
	if in == nil {
		return nil
	}
	out := new(FabricIBGPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricList) DeepCopyInto(out *FabricList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Fabric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricList.
func (in *FabricList) DeepCopy() *FabricList {
	if in == nil {
		return nil
	}
	out := new(FabricList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricLoopbacksSpec) DeepCopyInto(out *FabricLoopbacksSpec) {
	*out = *in
	out.IPAddressPoolRef = in.IPAddressPoolRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricLoopbacksSpec.
func (in *FabricLoopbacksSpec) DeepCopy() *FabricLoopbacksSpec {
	if in == nil {
		return nil
	}
	out := new(FabricLoopbacksSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricOverlaySpec) DeepCopyInto(out *FabricOverlaySpec) {
	*out = *in
	if in.IBGP != nil {
		in, out := &in.IBGP, &out.IBGP
		*out = new(FabricIBGPSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricOverlaySpec.
func (in *FabricOverlaySpec) DeepCopy() *FabricOverlaySpec {
	if in == nil {
		return nil
	}
	out := new(FabricOverlaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricPIMSpec) DeepCopyInto(out *FabricPIMSpec) {
	*out = *in
	if in.AnycastRendezvousPoints != nil {
		in, out := &in.AnycastRendezvousPoints, &out.AnycastRendezvousPoints
		*out = make([]AnycastRendezvousPoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricPIMSpec.
func (in *FabricPIMSpec) DeepCopy() *FabricPIMSpec {
	if in == nil {
		return nil
	}
	out := new(FabricPIMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricSpec) DeepCopyInto(out *FabricSpec) {
	*out = *in
	in.DeviceSelector.DeepCopyInto(&out.DeviceSelector)
	out.Loopbacks = in.Loopbacks
	in.Underlay.DeepCopyInto(&out.Underlay)
	in.Overlay.DeepCopyInto(&out.Overlay)
	in.BUM.DeepCopyInto(&out.BUM)
	in.VTEP.DeepCopyInto(&out.VTEP)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricSpec.
func (in *FabricSpec) DeepCopy() *FabricSpec {
	if in == nil {
		return nil
	}
	out := new(FabricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricStatus) DeepCopyInto(out *FabricStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricStatus.
func (in *FabricStatus) DeepCopy() *FabricStatus {
	if in == nil {
		return nil
	}
	out := new(FabricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricUnderlayAddressingSpec) DeepCopyInto(out *FabricUnderlayAddressingSpec) {
	*out = *in
	if in.IPPrefixPoolRef != nil {
		in, out := &in.IPPrefixPoolRef, &out.IPPrefixPoolRef
		*out = new(corev1alpha1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricUnderlayAddressingSpec.
func (in *FabricUnderlayAddressingSpec) DeepCopy() *FabricUnderlayAddressingSpec {
	if in == nil {
		return nil
	}
	out := new(FabricUnderlayAddressingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricUnderlaySpec) DeepCopyInto(out *FabricUnderlaySpec) {
	*out = *in
	in.InterfaceSelector.DeepCopyInto(&out.InterfaceSelector)
	in.Addressing.DeepCopyInto(&out.Addressing)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricUnderlaySpec.
func (in *FabricUnderlaySpec) DeepCopy() *FabricUnderlaySpec {
	if in == nil {
		return nil
	}
	out := new(FabricUnderlaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricVTEPSpec) DeepCopyInto(out *FabricVTEPSpec) {
	*out = *in
	in.DeviceSelector.DeepCopyInto(&out.DeviceSelector)
	if in.AnycastGateway != nil {
		in, out := &in.AnycastGateway, &out.AnycastGateway
		*out = new(FabricAnycastGatewaySpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricVTEPSpec.
func (in *FabricVTEPSpec) DeepCopy() *FabricVTEPSpec {
	if in == nil {
		return nil
	}
	out := new(FabricVTEPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteReflectorGroup) DeepCopyInto(out *RouteReflectorGroup) {
	*out = *in
	in.DeviceSelector.DeepCopyInto(&out.DeviceSelector)
	in.ClientDeviceSelector.DeepCopyInto(&out.ClientDeviceSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteReflectorGroup.
func (in *RouteReflectorGroup) DeepCopy() *RouteReflectorGroup {
	if in == nil {
		return nil
	}
	out := new(RouteReflectorGroup)
	in.DeepCopyInto(out)
	return out
}
