// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

package core

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"sync"
	"testing"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	coordinationv1 "k8s.io/api/coordination/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/sets"
	"k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/tools/events"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/envtest"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"

	"github.com/ironcore-dev/network-operator/api/core/v1alpha1"
	"github.com/ironcore-dev/network-operator/internal/deviceutil"
	"github.com/ironcore-dev/network-operator/internal/provider"
	"github.com/ironcore-dev/network-operator/internal/resourcelock"
	// +kubebuilder:scaffold:imports
)

// These tests use Ginkgo (BDD-style Go testing framework). Refer to
// http://onsi.github.io/ginkgo/ to learn more about Ginkgo.

var (
	ctx         context.Context
	cancel      context.CancelFunc
	testEnv     *envtest.Environment
	k8sClient   client.Client
	k8sManager  ctrl.Manager
	testDevices = NewDeviceStore()
	testLocker  *resourcelock.ResourceLocker
	// testEvents is a slice that stores events recorded during the tests. It is used to verify that the expected events are generated by the controllers.
	testEvents  []string
	testS3Store = NewMockObjectStorage()

	lastRebootTime = time.Date(2025, time.January, 1, 0, 0, 0, 0, time.UTC)
)

func TestControllers(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Core Controller Suite")
}

var _ = BeforeSuite(func() {
	logf.SetLogger(zap.New(zap.WriteTo(GinkgoWriter), zap.UseDevMode(true)))

	SetDefaultEventuallyTimeout(90 * time.Second)
	SetDefaultEventuallyPollingInterval(200 * time.Millisecond)

	ctx, cancel = context.WithCancel(ctrl.SetupSignalHandler())

	err := corev1.AddToScheme(scheme.Scheme)
	Expect(err).NotTo(HaveOccurred())

	err = v1alpha1.AddToScheme(scheme.Scheme)
	Expect(err).NotTo(HaveOccurred())

	// +kubebuilder:scaffold:scheme

	By("bootstrapping test environment")
	testEnv = &envtest.Environment{
		CRDDirectoryPaths:     []string{filepath.Join("..", "..", "..", "config", "crd", "bases")},
		ErrorIfCRDPathMissing: true,
	}

	// Retrieve the first found binary directory to allow running tests from IDEs
	if dir := detectTestBinaryDir(); dir != "" {
		testEnv.BinaryAssetsDirectory = dir
	}

	cfg, err := testEnv.Start()
	Expect(err).NotTo(HaveOccurred())
	Expect(cfg).NotTo(BeNil())

	k8sManager, err = ctrl.NewManager(cfg, ctrl.Options{
		Scheme:  scheme.Scheme,
		Logger:  GinkgoLogr,
		Metrics: metricsserver.Options{BindAddress: "0"},
	})
	Expect(err).ToNot(HaveOccurred())

	recorder := events.NewFakeRecorder(0)
	go func() {
		for event := range recorder.Events {
			GinkgoLogr.Info("Event", "event", event)
			testEvents = append(testEvents, event)
		}
	}()

	k8sClient, err = client.New(cfg, client.Options{Scheme: scheme.Scheme})
	Expect(err).NotTo(HaveOccurred())
	Expect(k8sClient).NotTo(BeNil())

	testLocker, err = resourcelock.NewResourceLocker(k8sManager.GetClient(), metav1.NamespaceDefault, 15*time.Second, 10*time.Second)
	Expect(err).NotTo(HaveOccurred())

	err = k8sManager.Add(testLocker)
	Expect(err).NotTo(HaveOccurred())

	// Set up cache informer for Lease resources used by ResourceLocker
	_, err = k8sManager.GetCache().GetInformer(ctx, &coordinationv1.Lease{})
	Expect(err).NotTo(HaveOccurred())

	prov := func() provider.Provider { return &Provider{devices: testDevices} }

	err = (&DeviceReconciler{
		Client:            k8sManager.GetClient(),
		Scheme:            k8sManager.GetScheme(),
		Recorder:          recorder,
		Provider:          prov,
		HeartbeatInterval: time.Second,
	}).SetupWithManager(k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&InterfaceReconciler{
		Client:          k8sManager.GetClient(),
		Scheme:          k8sManager.GetScheme(),
		Recorder:        recorder,
		Provider:        prov,
		Locker:          testLocker,
		RequeueInterval: time.Second,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&BannerReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&UserReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&DNSReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&NTPReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&AccessControlListReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&CertificateReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&SNMPReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&SyslogReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&ManagementAccessReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&ISISReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&VRFReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&PIMReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&BGPReconciler{
		Client:          k8sManager.GetClient(),
		Scheme:          k8sManager.GetScheme(),
		Recorder:        recorder,
		Provider:        prov,
		Locker:          testLocker,
		RequeueInterval: time.Second,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&BGPPeerReconciler{
		Client:          k8sManager.GetClient(),
		Scheme:          k8sManager.GetScheme(),
		Recorder:        recorder,
		Provider:        prov,
		Locker:          testLocker,
		RequeueInterval: time.Second,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&OSPFReconciler{
		Client:          k8sManager.GetClient(),
		Scheme:          k8sManager.GetScheme(),
		Recorder:        recorder,
		Provider:        prov,
		Locker:          testLocker,
		RequeueInterval: time.Second,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&VLANReconciler{
		Client:          k8sManager.GetClient(),
		Scheme:          k8sManager.GetScheme(),
		Recorder:        recorder,
		Provider:        prov,
		Locker:          testLocker,
		RequeueInterval: time.Second,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&EVPNInstanceReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&NetworkVirtualizationEdgeReconciler{
		Client:          k8sManager.GetClient(),
		Scheme:          k8sManager.GetScheme(),
		Recorder:        recorder,
		Provider:        prov,
		Locker:          testLocker,
		RequeueInterval: time.Second,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&PrefixSetReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&RoutingPolicyReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&LLDPReconciler{
		Client:          k8sManager.GetClient(),
		Scheme:          k8sManager.GetScheme(),
		Recorder:        recorder,
		Provider:        prov,
		Locker:          testLocker,
		RequeueInterval: time.Second,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&DHCPRelayReconciler{
		Client:          k8sManager.GetClient(),
		Scheme:          k8sManager.GetScheme(),
		Recorder:        recorder,
		Provider:        prov,
		Locker:          testLocker,
		RequeueInterval: time.Second,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&ConfigBackupReconciler{
		Client:        k8sManager.GetClient(),
		Scheme:        k8sManager.GetScheme(),
		Recorder:      recorder,
		Provider:      prov,
		Locker:        testLocker,
		ObjectStorage: testS3Store,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&EthernetSegmentReconciler{
		Client:          k8sManager.GetClient(),
		Scheme:          k8sManager.GetScheme(),
		Recorder:        recorder,
		Provider:        prov,
		Locker:          testLocker,
		RequeueInterval: time.Second,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	err = (&ProbeReconciler{
		Client:   k8sManager.GetClient(),
		Scheme:   k8sManager.GetScheme(),
		Recorder: recorder,
		Provider: prov,
		Locker:   testLocker,
	}).SetupWithManager(ctx, k8sManager)
	Expect(err).NotTo(HaveOccurred())

	go func() {
		defer GinkgoRecover()
		err = k8sManager.Start(ctx)
		Expect(err).ToNot(HaveOccurred(), "failed to run manager")
	}()

	Eventually(func() error {
		var namespace corev1.Namespace
		return k8sClient.Get(ctx, client.ObjectKey{Name: metav1.NamespaceDefault}, &namespace)
	}).Should(Succeed())
})

var _ = AfterSuite(func() {
	By("tearing down the test environment")
	cancel()
	err := testEnv.Stop()
	Expect(err).NotTo(HaveOccurred())
})

// detectTestBinaryDir locates the first binary in the specified path.
// ENVTEST-based tests depend on specific binaries, usually located in paths set by
// controller-runtime. When running tests directly (e.g., via an IDE) without using
// Makefile targets, the 'BinaryAssetsDirectory' must be explicitly configured.
//
// This function streamlines the process by finding the required binaries, similar to
// setting the 'KUBEBUILDER_ASSETS' environment variable. To ensure the binaries are
// properly set up, run 'make setup-envtest' beforehand.
func detectTestBinaryDir() string {
	basePath := filepath.Join("..", "..", "bin", "k8s")
	entries, err := os.ReadDir(basePath)
	if err != nil {
		logf.Log.Error(err, "Failed to read directory", "path", basePath)
		return ""
	}
	for _, entry := range entries {
		if entry.IsDir() {
			return filepath.Join(basePath, entry.Name())
		}
	}
	return ""
}

var (
	_ provider.Provider                 = (*Provider)(nil)
	_ provider.DeviceProvider           = (*Provider)(nil)
	_ provider.MaintenanceProvider      = (*Provider)(nil)
	_ provider.ProvisioningProvider     = (*Provider)(nil)
	_ provider.InterfaceProvider        = (*Provider)(nil)
	_ provider.BannerProvider           = (*Provider)(nil)
	_ provider.UserProvider             = (*Provider)(nil)
	_ provider.DNSProvider              = (*Provider)(nil)
	_ provider.NTPProvider              = (*Provider)(nil)
	_ provider.ACLProvider              = (*Provider)(nil)
	_ provider.CertificateProvider      = (*Provider)(nil)
	_ provider.SNMPProvider             = (*Provider)(nil)
	_ provider.SyslogProvider           = (*Provider)(nil)
	_ provider.ManagementAccessProvider = (*Provider)(nil)
	_ provider.ISISProvider             = (*Provider)(nil)
	_ provider.VRFProvider              = (*Provider)(nil)
	_ provider.PIMProvider              = (*Provider)(nil)
	_ provider.BGPProvider              = (*Provider)(nil)
	_ provider.BGPPeerProvider          = (*Provider)(nil)
	_ provider.OSPFProvider             = (*Provider)(nil)
	_ provider.VLANProvider             = (*Provider)(nil)
	_ provider.EVPNInstanceProvider     = (*Provider)(nil)
	_ provider.PrefixSetProvider        = (*Provider)(nil)
	_ provider.RoutingPolicyProvider    = (*Provider)(nil)
	_ provider.NVEProvider              = (*Provider)(nil)
	_ provider.LLDPProvider             = (*Provider)(nil)
	_ provider.DHCPRelayProvider        = (*Provider)(nil)
	_ provider.EthernetSegmentProvider  = (*Provider)(nil)
	_ provider.ConfigBackupProvider     = (*Provider)(nil)
	_ provider.ProbeProvider            = (*Provider)(nil)
)

// DeviceState holds per-device mutable state for testing. Each device created in
// a test gets its own DeviceState, preventing state bleed between test suites.
type DeviceState struct {
	sync.Mutex

	ConnectError   error // if non-nil, Connect returns this error
	LastRebootTime time.Time

	Ports            sets.Set[string]
	User             sets.Set[string]
	PreLoginBanner   *string
	PostLoginBanner  *string
	DNS              *v1alpha1.DNS
	NTP              *v1alpha1.NTP
	ACLs             sets.Set[string]
	Certs            sets.Set[string]
	SNMP             *v1alpha1.SNMP
	Syslog           *v1alpha1.Syslog
	Access           *v1alpha1.ManagementAccess
	ISIS             sets.Set[string]
	VRF              sets.Set[string]
	PIM              *v1alpha1.PIM
	BGP              *v1alpha1.BGP
	BGPVRF           *v1alpha1.VRF
	BGPPeers         sets.Set[string]
	OSPF             sets.Set[string]
	VLANs            sets.Set[int16]
	EVIs             sets.Set[int32]
	PrefixSets       sets.Set[string]
	RoutingPolicies  sets.Set[string]
	NVE              *v1alpha1.NetworkVirtualizationEdge
	LLDP             *v1alpha1.LLDP
	LLDPOperStatus   bool
	LLDPNeighbors    map[string]*provider.LLDPAdjacency
	DHCPRelay        *v1alpha1.DHCPRelay
	EthernetSegments map[string]string
	StartupConfig    *v1alpha1.ConfigBackup
	ConfigBackups    []*provider.ConfigBackupFile
	StorageTotal     int64
}

func NewDeviceState() *DeviceState {
	return &DeviceState{
		LastRebootTime:   lastRebootTime,
		Ports:            sets.New[string](),
		User:             sets.New[string](),
		ACLs:             sets.New[string](),
		Certs:            sets.New[string](),
		ISIS:             sets.New[string](),
		VRF:              sets.New[string](),
		BGPPeers:         sets.New[string](),
		OSPF:             sets.New[string](),
		VLANs:            sets.New[int16](),
		EVIs:             sets.New[int32](),
		PrefixSets:       sets.New[string](),
		RoutingPolicies:  sets.New[string](),
		LLDPOperStatus:   true,
		LLDPNeighbors:    make(map[string]*provider.LLDPAdjacency),
		EthernetSegments: make(map[string]string),
		StorageTotal:     int64(1024 * 1024 * 100),
	}
}

// DeviceStore holds per-device state for all test devices, keyed by device name.
type DeviceStore struct {
	sync.Mutex
	states map[string]*DeviceState
}

func NewDeviceStore() *DeviceStore {
	return &DeviceStore{states: make(map[string]*DeviceState)}
}

// StateFor returns the DeviceState for the given device name, creating one if it doesn't exist.
func (s *DeviceStore) StateFor(name string) *DeviceState {
	s.Lock()
	defer s.Unlock()
	ds, ok := s.states[name]
	if !ok {
		ds = NewDeviceState()
		s.states[name] = ds
	}
	return ds
}

// Provider is an in-memory provider for testing. The ProviderFunc factory creates
// a new Provider per reconcile call, sharing the DeviceStore. Connect captures the
// device name from the Connection so subsequent method calls dispatch to the correct
// DeviceState.
type Provider struct {
	devices    *DeviceStore
	deviceName string // set during Connect
}

// SetConnectFailure sets the error that Connect will return for this device.
func (s *DeviceState) SetConnectFailure(err error) {
	s.Lock()
	defer s.Unlock()
	s.ConnectError = err
}

// SetLastRebootTime sets the time returned by GetLastRebootTime for this device.
func (s *DeviceState) SetLastRebootTime(t time.Time) {
	s.Lock()
	defer s.Unlock()
	s.LastRebootTime = t
}

func (p *Provider) Connect(_ context.Context, conn *deviceutil.Connection) error {
	s := p.devices.StateFor(conn.DeviceName)
	s.Lock()
	err := s.ConnectError
	s.Unlock()
	if err != nil {
		return err
	}
	p.deviceName = conn.DeviceName
	return nil
}

func (p *Provider) Disconnect(context.Context, *deviceutil.Connection) error { return nil }

func (p *Provider) ListPorts(context.Context) (ports []provider.DevicePort, err error) {
	for i := range 8 {
		ports = append(ports, provider.DevicePort{
			ID:                  "eth1/" + strconv.Itoa(i+1),
			Type:                "10g",
			SupportedSpeedsGbps: []int32{1, 10},
			Transceiver:         "QSFP-DD",
		})
	}
	return
}

func (p *Provider) GetLastRebootTime(_ context.Context) (time.Time, error) {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	return s.LastRebootTime, nil
}

func (p *Provider) GetDeviceInfo(context.Context) (*provider.DeviceInfo, error) {
	return &provider.DeviceInfo{
		Manufacturer:    "Manufacturer",
		Model:           "Model",
		SerialNumber:    "123456789",
		FirmwareVersion: "1.0.0",
	}, nil
}

func (p *Provider) HashProvisioningPassword(password string) (hashed, encryptType string, err error) {
	return password, "plain", nil
}

func (p *Provider) VerifyProvisioned(context.Context, *deviceutil.Connection, *v1alpha1.Device) bool {
	return true
}

func (p *Provider) Reboot(context.Context, *deviceutil.Connection) error {
	return nil
}

func (p *Provider) FactoryReset(context.Context, *deviceutil.Connection) error {
	return nil
}

func (p *Provider) Reprovision(context.Context, *deviceutil.Connection) error {
	return nil
}

func (p *Provider) EnsureInterface(_ context.Context, req *provider.EnsureInterfaceRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.Ports.Insert(req.Interface.Spec.Name)
	return nil
}

func (p *Provider) DeleteInterface(_ context.Context, req *provider.InterfaceRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.Ports.Delete(req.Interface.Spec.Name)
	return nil
}

func (p *Provider) GetInterfaceStatus(_ context.Context, req *provider.InterfaceRequest) (provider.InterfaceStatus, error) {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	status := provider.InterfaceStatus{OperStatus: true}
	if neighbor, ok := s.LLDPNeighbors[req.Interface.Spec.Name]; ok {
		status.LLDPAdjacencies = []provider.LLDPAdjacency{*neighbor}
	}
	return status, nil
}

func (p *Provider) InterfaceNameEqual(_ context.Context, a, b string) (bool, error) {
	return a == b, nil
}

func (p *Provider) LoopbackInterfaceName(id int) (string, error) {
	return fmt.Sprintf("lo%d", id), nil
}

func (p *Provider) EnsureBanner(_ context.Context, req *provider.EnsureBannerRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	switch req.Type {
	case v1alpha1.BannerTypePreLogin:
		s.PreLoginBanner = &req.Message
	case v1alpha1.BannerTypePostLogin:
		s.PostLoginBanner = &req.Message
	default:
		return errors.New("unknown banner type")
	}
	return nil
}

func (p *Provider) DeleteBanner(_ context.Context, req *provider.DeleteBannerRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	switch req.Type {
	case v1alpha1.BannerTypePreLogin:
		s.PreLoginBanner = nil
	case v1alpha1.BannerTypePostLogin:
		s.PostLoginBanner = nil
	default:
		return errors.New("unknown banner type")
	}
	return nil
}

func (p *Provider) EnsureUser(_ context.Context, req *provider.EnsureUserRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.User.Insert(req.Username)
	return nil
}

func (p *Provider) DeleteUser(_ context.Context, req *provider.DeleteUserRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.User.Delete(req.Username)
	return nil
}

func (p *Provider) EnsureDNS(_ context.Context, req *provider.EnsureDNSRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.DNS = req.DNS
	return nil
}

func (p *Provider) DeleteDNS(_ context.Context) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.DNS = nil
	return nil
}

func (p *Provider) EnsureNTP(_ context.Context, req *provider.EnsureNTPRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.NTP = req.NTP
	return nil
}

func (p *Provider) DeleteNTP(context.Context) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.NTP = nil
	return nil
}

func (p *Provider) EnsureACL(_ context.Context, req *provider.ACLRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.ACLs.Insert(req.ACL.Spec.Name)
	return nil
}

func (p *Provider) DeleteACL(_ context.Context, req *provider.ACLRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.ACLs.Delete(req.ACL.Spec.Name)
	return nil
}

func (p *Provider) EnsureCertificate(_ context.Context, req *provider.EnsureCertificateRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.Certs.Insert(req.ID)
	return nil
}

func (p *Provider) DeleteCertificate(_ context.Context, req *provider.DeleteCertificateRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.Certs.Delete(req.ID)
	return nil
}

func (p *Provider) EnsureSNMP(_ context.Context, req *provider.EnsureSNMPRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.SNMP = req.SNMP
	return nil
}

func (p *Provider) DeleteSNMP(_ context.Context, req *provider.DeleteSNMPRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.SNMP = nil
	return nil
}

func (p *Provider) EnsureSyslog(_ context.Context, req *provider.EnsureSyslogRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.Syslog = req.Syslog
	return nil
}

func (p *Provider) DeleteSyslog(_ context.Context) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.Syslog = nil
	return nil
}

func (p *Provider) EnsureManagementAccess(_ context.Context, req *provider.EnsureManagementAccessRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.Access = req.ManagementAccess
	return nil
}

func (p *Provider) DeleteManagementAccess(context.Context, *provider.DeleteManagementAccessRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.Access = nil
	return nil
}

func (p *Provider) EnsureISIS(_ context.Context, req *provider.EnsureISISRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.ISIS.Insert(req.ISIS.Spec.Instance)
	return nil
}

func (p *Provider) DeleteISIS(_ context.Context, req *provider.DeleteISISRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.ISIS.Delete(req.ISIS.Spec.Instance)
	return nil
}

func (p *Provider) EnsureVRF(_ context.Context, req *provider.VRFRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.VRF.Insert(req.VRF.Spec.Name)
	return nil
}

func (p *Provider) DeleteVRF(_ context.Context, req *provider.VRFRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.VRF.Delete(req.VRF.Spec.Name)
	return nil
}

func (p *Provider) EnsurePIM(_ context.Context, req *provider.EnsurePIMRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.PIM = req.PIM
	return nil
}

func (p *Provider) DeletePIM(context.Context, *provider.DeletePIMRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.PIM = nil
	return nil
}

func (p *Provider) EnsureBGP(_ context.Context, req *provider.EnsureBGPRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.BGP = req.BGP
	s.BGPVRF = req.VRF
	return nil
}

func (p *Provider) DeleteBGP(context.Context, *provider.DeleteBGPRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.BGP = nil
	s.BGPVRF = nil
	return nil
}

func (p *Provider) EnsureBGPPeer(_ context.Context, req *provider.EnsureBGPPeerRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.BGPPeers.Insert(req.BGPPeer.Spec.Address)
	return nil
}

func (p *Provider) DeleteBGPPeer(_ context.Context, req *provider.DeleteBGPPeerRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.BGPPeers.Delete(req.BGPPeer.Spec.Address)
	return nil
}

func (p *Provider) GetPeerStatus(context.Context, *provider.BGPPeerStatusRequest) (provider.BGPPeerStatus, error) {
	return provider.BGPPeerStatus{
		SessionState:        v1alpha1.BGPPeerSessionStateEstablished,
		LastEstablishedTime: time.Now().Add(-5 * time.Minute),
		AddressFamilies: map[v1alpha1.BGPAddressFamilyType]*provider.PrefixStats{
			v1alpha1.BGPAddressFamilyL2vpnEvpn: {
				Accepted:   10,
				Advertised: 10,
			},
		},
	}, nil
}

func (p *Provider) EnsureOSPF(_ context.Context, req *provider.EnsureOSPFRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.OSPF.Insert(req.OSPF.Spec.Instance)
	return nil
}

func (p *Provider) DeleteOSPF(_ context.Context, req *provider.DeleteOSPFRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.OSPF.Delete(req.OSPF.Spec.Instance)
	return nil
}

func (p *Provider) GetOSPFStatus(context.Context, *provider.OSPFStatusRequest) (provider.OSPFStatus, error) {
	return provider.OSPFStatus{OperStatus: true}, nil
}

func (p *Provider) EnsureVLAN(_ context.Context, req *provider.VLANRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.VLANs.Insert(req.VLAN.Spec.ID)
	return nil
}

func (p *Provider) DeleteVLAN(_ context.Context, req *provider.VLANRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.VLANs.Delete(req.VLAN.Spec.ID)
	return nil
}

func (p *Provider) GetVLANStatus(context.Context, *provider.VLANRequest) (provider.VLANStatus, error) {
	return provider.VLANStatus{OperStatus: true}, nil
}

func (p *Provider) EnsureEVPNInstance(_ context.Context, req *provider.EVPNInstanceRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.EVIs.Insert(req.EVPNInstance.Spec.VNI)
	return nil
}

func (p *Provider) DeleteEVPNInstance(_ context.Context, req *provider.EVPNInstanceRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.EVIs.Delete(req.EVPNInstance.Spec.VNI)
	return nil
}

func (p *Provider) EnsurePrefixSet(_ context.Context, req *provider.PrefixSetRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.PrefixSets.Insert(req.PrefixSet.Spec.Name)
	return nil
}

func (p *Provider) DeletePrefixSet(_ context.Context, req *provider.PrefixSetRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.PrefixSets.Delete(req.PrefixSet.Spec.Name)
	return nil
}

func (p *Provider) EnsureRoutingPolicy(_ context.Context, req *provider.EnsureRoutingPolicyRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.RoutingPolicies.Insert(req.Name)
	return nil
}

func (p *Provider) DeleteRoutingPolicy(_ context.Context, req *provider.DeleteRoutingPolicyRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.RoutingPolicies.Delete(req.Name)
	return nil
}

func (p *Provider) EnsureNVE(_ context.Context, req *provider.NVERequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.NVE = req.NVE
	return nil
}

func (p *Provider) DeleteNVE(_ context.Context, req *provider.NVERequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.NVE = nil
	return nil
}

func (p *Provider) GetNVEStatus(_ context.Context, _ *provider.NVERequest) (provider.NVEStatus, error) {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	status := provider.NVEStatus{OperStatus: true}
	if s.NVE != nil {
		if s.NVE.Spec.SourceInterfaceRef.Name != "" {
			status.SourceInterfaceName = s.NVE.Spec.SourceInterfaceRef.Name
		}
		if s.NVE.Spec.AnycastSourceInterfaceRef != nil {
			status.AnycastSourceInterfaceName = s.NVE.Spec.AnycastSourceInterfaceRef.Name
		}
	}
	return status, nil
}

func (p *Provider) RunningConfig(context.Context) ([]byte, error) {
	return []byte("! running-config mock\nhostname test-device\n"), nil
}

func (p *Provider) CreateConfigBackup(_ context.Context, req *provider.ConfigBackupRequest) (*provider.ConfigBackupFile, error) {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	if req.ConfigBackup.Spec.Type == v1alpha1.ConfigBackupTypeStartup {
		s.StartupConfig = req.ConfigBackup
		return nil, nil //nolint:nilnil
	}
	file := &provider.ConfigBackupFile{
		Path:      path.Join(req.ConfigBackup.Spec.Path, fmt.Sprintf("configbackup-%s-", req.ConfigBackup.UID)) + time.Now().Format("20060102T150405Z"),
		SizeBytes: new(int64(1024)),
		CreatedAt: time.Now(),
	}
	s.ConfigBackups = append(s.ConfigBackups, file)
	return file, nil
}

func (p *Provider) ListConfigBackups(_ context.Context, _ *provider.ConfigBackupRequest) (*provider.ConfigBackupInventory, error) {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	var used int64
	for _, f := range s.ConfigBackups {
		if f.SizeBytes != nil {
			used += *f.SizeBytes
		}
	}
	return &provider.ConfigBackupInventory{
		Backups:    s.ConfigBackups,
		TotalBytes: &s.StorageTotal,
		UsedBytes:  &used,
		FreeBytes:  new(s.StorageTotal - used),
	}, nil
}

func (p *Provider) DeleteConfigBackups(_ context.Context, files ...*provider.ConfigBackupFile) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	remove := make(map[string]struct{}, len(files))
	for _, f := range files {
		remove[f.Path] = struct{}{}
	}
	filtered := s.ConfigBackups[:0]
	for _, b := range s.ConfigBackups {
		if _, ok := remove[b.Path]; !ok {
			filtered = append(filtered, b)
		}
	}
	s.ConfigBackups = filtered
	return nil
}

func (p *Provider) EnsureLLDP(_ context.Context, req *provider.LLDPRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.LLDP = req.LLDP
	return nil
}

func (p *Provider) DeleteLLDP(_ context.Context, req *provider.LLDPRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.LLDP = nil
	return nil
}

func (p *Provider) GetLLDPStatus(_ context.Context, _ *provider.LLDPRequest) (provider.LLDPStatus, error) {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	return provider.LLDPStatus{OperStatus: s.LLDPOperStatus}, nil
}

func (p *Provider) EnsureDHCPRelay(_ context.Context, req *provider.DHCPRelayRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.DHCPRelay = req.DHCPRelay
	return nil
}

func (p *Provider) DeleteDHCPRelay(_ context.Context, req *provider.DHCPRelayRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	s.DHCPRelay = nil
	return nil
}

func (p *Provider) GetDHCPRelayStatus(_ context.Context, req *provider.DHCPRelayRequest) (provider.DHCPRelayStatus, error) {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	status := provider.DHCPRelayStatus{}
	if s.DHCPRelay != nil {
		for _, intf := range req.Interfaces {
			status.ConfiguredInterfaces = append(status.ConfiguredInterfaces, intf.Spec.Name)
		}
	}
	return status, nil
}

func (p *Provider) EnsureEthernetSegment(_ context.Context, req *provider.EnsureEthernetSegmentRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	esi := req.EthernetSegment.Spec.ESI
	if esi == "" {
		// Simulate auto-generated ESI (Type 3 MAC-based)
		esi = "03:aa:bb:cc:dd:ee:ff:00:00:01"
	}
	s.EthernetSegments[req.EthernetSegment.Name] = esi
	return nil
}

func (p *Provider) DeleteEthernetSegment(_ context.Context, req *provider.DeleteEthernetSegmentRequest) error {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	delete(s.EthernetSegments, req.EthernetSegment.Name)
	return nil
}

func (p *Provider) GetEthernetSegmentStatus(_ context.Context, req *provider.EthernetSegmentStatusRequest) (provider.EthernetSegmentStatus, error) {
	s := p.devices.StateFor(p.deviceName)
	s.Lock()
	defer s.Unlock()
	esi := s.EthernetSegments[req.EthernetSegment.Name]
	return provider.EthernetSegmentStatus{ESI: esi, OperStatus: esi != ""}, nil
}

// GetEthernetSegment is a test helper to retrieve the ESI for an ethernet segment by name.
func (s *DeviceState) GetEthernetSegment(name string) (string, bool) {
	s.Lock()
	defer s.Unlock()
	esi, ok := s.EthernetSegments[name]
	return esi, ok
}

func (p *Provider) Ping(context.Context, *provider.PingRequest) (*provider.PingStats, error) {
	return &provider.PingStats{
		Sent:     3,
		Received: 3,
		MinTime:  time.Millisecond,
		AvgTime:  time.Millisecond,
		MaxTime:  time.Millisecond,
	}, nil
}

func (p *Provider) GetMACTable(context.Context, *provider.MACTableRequest) ([]provider.MACTableEntry, error) {
	return []provider.MACTableEntry{{MACAddress: "00:1a:2b:3c:4d:5e"}}, nil
}

func (p *Provider) GetRouteTable(context.Context, *provider.RouteTableRequest) ([]provider.RouteEntry, error) {
	return []provider.RouteEntry{{Prefix: "10.100.0.0/16"}}, nil
}

func (p *Provider) GetVTEPPeers(context.Context, *provider.VTEPPeersRequest) ([]provider.VTEPPeer, error) {
	return []provider.VTEPPeer{{PeerIP: "192.0.2.10", OperStatus: true}}, nil
}

// SetLLDPNeighbor is a test helper to configure LLDP neighbor information for an interface.
func (s *DeviceState) SetLLDPNeighbor(interfaceName, sysName, chassisID, portID string, ttl uint32) {
	s.Lock()
	defer s.Unlock()
	s.LLDPNeighbors[interfaceName] = &provider.LLDPAdjacency{
		SysName:       sysName,
		ChassisID:     chassisID,
		ChassisIDType: 4, // MACAddress
		PortID:        portID,
		PortIDType:    7, // Local
		TTL:           time.Duration(ttl) * time.Second,
	}
}
