// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package nxapi

import (
	"context"
	"encoding/json"
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			CloneFunc: func(options ...Option) (Client, error) {
//				panic("mock out the Clone method")
//			},
//			DoFunc: func(contextMoqParam context.Context, request Request) ([]json.RawMessage, error) {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// CloneFunc mocks the Clone method.
	CloneFunc func(options ...Option) (Client, error)

	// DoFunc mocks the Do method.
	DoFunc func(contextMoqParam context.Context, request Request) ([]json.RawMessage, error)

	// calls tracks calls to the methods.
	calls struct {
		// Clone holds details about calls to the Clone method.
		Clone []struct {
			// Options is the options argument value.
			Options []Option
		}
		// Do holds details about calls to the Do method.
		Do []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Request is the request argument value.
			Request Request
		}
	}
	lockClone sync.RWMutex
	lockDo    sync.RWMutex
}

// Clone calls CloneFunc.
func (mock *ClientMock) Clone(options ...Option) (Client, error) {
	if mock.CloneFunc == nil {
		panic("ClientMock.CloneFunc: method is nil but Client.Clone was just called")
	}
	callInfo := struct {
		Options []Option
	}{
		Options: options,
	}
	mock.lockClone.Lock()
	mock.calls.Clone = append(mock.calls.Clone, callInfo)
	mock.lockClone.Unlock()
	return mock.CloneFunc(options...)
}

// CloneCalls gets all the calls that were made to Clone.
// Check the length with:
//
//	len(mockedClient.CloneCalls())
func (mock *ClientMock) CloneCalls() []struct {
	Options []Option
} {
	var calls []struct {
		Options []Option
	}
	mock.lockClone.RLock()
	calls = mock.calls.Clone
	mock.lockClone.RUnlock()
	return calls
}

// ResetCloneCalls reset all the calls that were made to Clone.
func (mock *ClientMock) ResetCloneCalls() {
	mock.lockClone.Lock()
	mock.calls.Clone = nil
	mock.lockClone.Unlock()
}

// Do calls DoFunc.
func (mock *ClientMock) Do(contextMoqParam context.Context, request Request) ([]json.RawMessage, error) {
	if mock.DoFunc == nil {
		panic("ClientMock.DoFunc: method is nil but Client.Do was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Request         Request
	}{
		ContextMoqParam: contextMoqParam,
		Request:         request,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(contextMoqParam, request)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedClient.DoCalls())
func (mock *ClientMock) DoCalls() []struct {
	ContextMoqParam context.Context
	Request         Request
} {
	var calls []struct {
		ContextMoqParam context.Context
		Request         Request
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}

// ResetDoCalls reset all the calls that were made to Do.
func (mock *ClientMock) ResetDoCalls() {
	mock.lockDo.Lock()
	mock.calls.Do = nil
	mock.lockDo.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ClientMock) ResetCalls() {
	mock.lockClone.Lock()
	mock.calls.Clone = nil
	mock.lockClone.Unlock()

	mock.lockDo.Lock()
	mock.calls.Do = nil
	mock.lockDo.Unlock()
}
