apiVersion: overlay.networking.metal.ironcore.dev/v1alpha1
kind: Network
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: network-sample
spec: {}
