apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: ExtCommunitySet
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: extcommunityset
spec:
  deviceRef:
    name: leaf1
  name: WIREAPI
  members:
    - sequence: 5
      regex: "65200:[0-9][0-9]"
    - sequence: 15
      regex: "65300:[0-9]+"
