// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package gnmiext

import (
	"context"
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			CapabilitiesFunc: func() *Capabilities {
//				panic("mock out the Capabilities method")
//			},
//			DeleteFunc: func(contextMoqParam context.Context, dataElements ...DataElement) error {
//				panic("mock out the Delete method")
//			},
//			DoFunc: func(contextMoqParam context.Context, setBuilder *SetBuilder) error {
//				panic("mock out the Do method")
//			},
//			GetConfigFunc: func(contextMoqParam context.Context, dataElements ...DataElement) error {
//				panic("mock out the GetConfig method")
//			},
//			GetStateFunc: func(contextMoqParam context.Context, dataElements ...DataElement) error {
//				panic("mock out the GetState method")
//			},
//			PatchFunc: func(contextMoqParam context.Context, dataElements ...DataElement) error {
//				panic("mock out the Patch method")
//			},
//			UpdateFunc: func(contextMoqParam context.Context, dataElements ...DataElement) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// CapabilitiesFunc mocks the Capabilities method.
	CapabilitiesFunc func() *Capabilities

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(contextMoqParam context.Context, dataElements ...DataElement) error

	// DoFunc mocks the Do method.
	DoFunc func(contextMoqParam context.Context, setBuilder *SetBuilder) error

	// GetConfigFunc mocks the GetConfig method.
	GetConfigFunc func(contextMoqParam context.Context, dataElements ...DataElement) error

	// GetStateFunc mocks the GetState method.
	GetStateFunc func(contextMoqParam context.Context, dataElements ...DataElement) error

	// PatchFunc mocks the Patch method.
	PatchFunc func(contextMoqParam context.Context, dataElements ...DataElement) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(contextMoqParam context.Context, dataElements ...DataElement) error

	// calls tracks calls to the methods.
	calls struct {
		// Capabilities holds details about calls to the Capabilities method.
		Capabilities []struct{}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DataElements is the dataElements argument value.
			DataElements []DataElement
		}
		// Do holds details about calls to the Do method.
		Do []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// SetBuilder is the setBuilder argument value.
			SetBuilder *SetBuilder
		}
		// GetConfig holds details about calls to the GetConfig method.
		GetConfig []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DataElements is the dataElements argument value.
			DataElements []DataElement
		}
		// GetState holds details about calls to the GetState method.
		GetState []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DataElements is the dataElements argument value.
			DataElements []DataElement
		}
		// Patch holds details about calls to the Patch method.
		Patch []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DataElements is the dataElements argument value.
			DataElements []DataElement
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DataElements is the dataElements argument value.
			DataElements []DataElement
		}
	}
	lockCapabilities sync.RWMutex
	lockDelete       sync.RWMutex
	lockDo           sync.RWMutex
	lockGetConfig    sync.RWMutex
	lockGetState     sync.RWMutex
	lockPatch        sync.RWMutex
	lockUpdate       sync.RWMutex
}

// Capabilities calls CapabilitiesFunc.
func (mock *ClientMock) Capabilities() *Capabilities {
	if mock.CapabilitiesFunc == nil {
		panic("ClientMock.CapabilitiesFunc: method is nil but Client.Capabilities was just called")
	}
	callInfo := struct{}{}
	mock.lockCapabilities.Lock()
	mock.calls.Capabilities = append(mock.calls.Capabilities, callInfo)
	mock.lockCapabilities.Unlock()
	return mock.CapabilitiesFunc()
}

// CapabilitiesCalls gets all the calls that were made to Capabilities.
// Check the length with:
//
//	len(mockedClient.CapabilitiesCalls())
func (mock *ClientMock) CapabilitiesCalls() []struct{} {
	var calls []struct{}
	mock.lockCapabilities.RLock()
	calls = mock.calls.Capabilities
	mock.lockCapabilities.RUnlock()
	return calls
}

// ResetCapabilitiesCalls reset all the calls that were made to Capabilities.
func (mock *ClientMock) ResetCapabilitiesCalls() {
	mock.lockCapabilities.Lock()
	mock.calls.Capabilities = nil
	mock.lockCapabilities.Unlock()
}

// Delete calls DeleteFunc.
func (mock *ClientMock) Delete(contextMoqParam context.Context, dataElements ...DataElement) error {
	if mock.DeleteFunc == nil {
		panic("ClientMock.DeleteFunc: method is nil but Client.Delete was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		DataElements    []DataElement
	}{
		ContextMoqParam: contextMoqParam,
		DataElements:    dataElements,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(contextMoqParam, dataElements...)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedClient.DeleteCalls())
func (mock *ClientMock) DeleteCalls() []struct {
	ContextMoqParam context.Context
	DataElements    []DataElement
} {
	var calls []struct {
		ContextMoqParam context.Context
		DataElements    []DataElement
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *ClientMock) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// Do calls DoFunc.
func (mock *ClientMock) Do(contextMoqParam context.Context, setBuilder *SetBuilder) error {
	if mock.DoFunc == nil {
		panic("ClientMock.DoFunc: method is nil but Client.Do was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		SetBuilder      *SetBuilder
	}{
		ContextMoqParam: contextMoqParam,
		SetBuilder:      setBuilder,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(contextMoqParam, setBuilder)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedClient.DoCalls())
func (mock *ClientMock) DoCalls() []struct {
	ContextMoqParam context.Context
	SetBuilder      *SetBuilder
} {
	var calls []struct {
		ContextMoqParam context.Context
		SetBuilder      *SetBuilder
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}

// ResetDoCalls reset all the calls that were made to Do.
func (mock *ClientMock) ResetDoCalls() {
	mock.lockDo.Lock()
	mock.calls.Do = nil
	mock.lockDo.Unlock()
}

// GetConfig calls GetConfigFunc.
func (mock *ClientMock) GetConfig(contextMoqParam context.Context, dataElements ...DataElement) error {
	if mock.GetConfigFunc == nil {
		panic("ClientMock.GetConfigFunc: method is nil but Client.GetConfig was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		DataElements    []DataElement
	}{
		ContextMoqParam: contextMoqParam,
		DataElements:    dataElements,
	}
	mock.lockGetConfig.Lock()
	mock.calls.GetConfig = append(mock.calls.GetConfig, callInfo)
	mock.lockGetConfig.Unlock()
	return mock.GetConfigFunc(contextMoqParam, dataElements...)
}

// GetConfigCalls gets all the calls that were made to GetConfig.
// Check the length with:
//
//	len(mockedClient.GetConfigCalls())
func (mock *ClientMock) GetConfigCalls() []struct {
	ContextMoqParam context.Context
	DataElements    []DataElement
} {
	var calls []struct {
		ContextMoqParam context.Context
		DataElements    []DataElement
	}
	mock.lockGetConfig.RLock()
	calls = mock.calls.GetConfig
	mock.lockGetConfig.RUnlock()
	return calls
}

// ResetGetConfigCalls reset all the calls that were made to GetConfig.
func (mock *ClientMock) ResetGetConfigCalls() {
	mock.lockGetConfig.Lock()
	mock.calls.GetConfig = nil
	mock.lockGetConfig.Unlock()
}

// GetState calls GetStateFunc.
func (mock *ClientMock) GetState(contextMoqParam context.Context, dataElements ...DataElement) error {
	if mock.GetStateFunc == nil {
		panic("ClientMock.GetStateFunc: method is nil but Client.GetState was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		DataElements    []DataElement
	}{
		ContextMoqParam: contextMoqParam,
		DataElements:    dataElements,
	}
	mock.lockGetState.Lock()
	mock.calls.GetState = append(mock.calls.GetState, callInfo)
	mock.lockGetState.Unlock()
	return mock.GetStateFunc(contextMoqParam, dataElements...)
}

// GetStateCalls gets all the calls that were made to GetState.
// Check the length with:
//
//	len(mockedClient.GetStateCalls())
func (mock *ClientMock) GetStateCalls() []struct {
	ContextMoqParam context.Context
	DataElements    []DataElement
} {
	var calls []struct {
		ContextMoqParam context.Context
		DataElements    []DataElement
	}
	mock.lockGetState.RLock()
	calls = mock.calls.GetState
	mock.lockGetState.RUnlock()
	return calls
}

// ResetGetStateCalls reset all the calls that were made to GetState.
func (mock *ClientMock) ResetGetStateCalls() {
	mock.lockGetState.Lock()
	mock.calls.GetState = nil
	mock.lockGetState.Unlock()
}

// Patch calls PatchFunc.
func (mock *ClientMock) Patch(contextMoqParam context.Context, dataElements ...DataElement) error {
	if mock.PatchFunc == nil {
		panic("ClientMock.PatchFunc: method is nil but Client.Patch was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		DataElements    []DataElement
	}{
		ContextMoqParam: contextMoqParam,
		DataElements:    dataElements,
	}
	mock.lockPatch.Lock()
	mock.calls.Patch = append(mock.calls.Patch, callInfo)
	mock.lockPatch.Unlock()
	return mock.PatchFunc(contextMoqParam, dataElements...)
}

// PatchCalls gets all the calls that were made to Patch.
// Check the length with:
//
//	len(mockedClient.PatchCalls())
func (mock *ClientMock) PatchCalls() []struct {
	ContextMoqParam context.Context
	DataElements    []DataElement
} {
	var calls []struct {
		ContextMoqParam context.Context
		DataElements    []DataElement
	}
	mock.lockPatch.RLock()
	calls = mock.calls.Patch
	mock.lockPatch.RUnlock()
	return calls
}

// ResetPatchCalls reset all the calls that were made to Patch.
func (mock *ClientMock) ResetPatchCalls() {
	mock.lockPatch.Lock()
	mock.calls.Patch = nil
	mock.lockPatch.Unlock()
}

// Update calls UpdateFunc.
func (mock *ClientMock) Update(contextMoqParam context.Context, dataElements ...DataElement) error {
	if mock.UpdateFunc == nil {
		panic("ClientMock.UpdateFunc: method is nil but Client.Update was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		DataElements    []DataElement
	}{
		ContextMoqParam: contextMoqParam,
		DataElements:    dataElements,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(contextMoqParam, dataElements...)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedClient.UpdateCalls())
func (mock *ClientMock) UpdateCalls() []struct {
	ContextMoqParam context.Context
	DataElements    []DataElement
} {
	var calls []struct {
		ContextMoqParam context.Context
		DataElements    []DataElement
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *ClientMock) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ClientMock) ResetCalls() {
	mock.lockCapabilities.Lock()
	mock.calls.Capabilities = nil
	mock.lockCapabilities.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockDo.Lock()
	mock.calls.Do = nil
	mock.lockDo.Unlock()

	mock.lockGetConfig.Lock()
	mock.calls.GetConfig = nil
	mock.lockGetConfig.Unlock()

	mock.lockGetState.Lock()
	mock.calls.GetState = nil
	mock.lockGetState.Unlock()

	mock.lockPatch.Lock()
	mock.calls.Patch = nil
	mock.lockPatch.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}
