//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTEPConfig) DeepCopyInto(out *VTEPConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTEPConfig.
func (in *VTEPConfig) DeepCopy() *VTEPConfig {
	if in == nil {
		return nil
	}
	out := new(VTEPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VTEPConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTEPConfigList) DeepCopyInto(out *VTEPConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VTEPConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTEPConfigList.
func (in *VTEPConfigList) DeepCopy() *VTEPConfigList {
	if in == nil {
		return nil
	}
	out := new(VTEPConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VTEPConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTEPConfigSpec) DeepCopyInto(out *VTEPConfigSpec) {
	*out = *in
	if in.AdvertiseVMAC != nil {
		in, out := &in.AdvertiseVMAC, &out.AdvertiseVMAC
		*out = new(bool)
		**out = **in
	}
	if in.InfraVLANs != nil {
		in, out := &in.InfraVLANs, &out.InfraVLANs
		*out = make([]VLANListItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTEPConfigSpec.
func (in *VTEPConfigSpec) DeepCopy() *VTEPConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VTEPConfigSpec)
	in.DeepCopyInto(out)
	return out
}
