apiVersion: nx.cisco.networking.metal.ironcore.dev/v1alpha1
kind: PIMConfig
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: leaf1-pimconfig
spec:
  logNeighborChanges: true
