apiVersion: nx.cisco.networking.metal.ironcore.dev/v1alpha1
kind: EthernetSegmentConfig
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: ethernetsegmentconfig-frr
spec:
  frrAnycastSourceIP: "10.0.0.1"
