// Code generated by "stringer -type=ISISType"; DO NOT EDIT.

package isis

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Level1-1]
	_ = x[Level2-2]
	_ = x[Level12-3]
}

const _ISISType_name = "Level1Level2Level12"

var _ISISType_index = [...]uint8{0, 6, 12, 19}

func (i ISISType) String() string {
	i -= 1
	if i < 0 || i >= ISISType(len(_ISISType_index)-1) {
		return "ISISType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ISISType_name[_ISISType_index[i]:_ISISType_index[i+1]]
}
