#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
# SPDX-License-Identifier: Apache-2.0

cd "$(dirname "$0")" || exit 1

version="10.4-3"
alt_version_name=$(echo "$version" | tr '.' '_' |  tr '-' '_')

model="${alt_version_name}/Cisco-NX-OS-device.yang"

mkdir -p "./${alt_version_name}"
if [ ! -f "$model" ]; then
  echo "Downloading Cisco-NX-OS-device.yang..."
  curl -fsSL https://raw.githubusercontent.com/YangModels/yang/refs/heads/main/vendor/cisco/nx/$version/Cisco-NX-OS-device.yang -o "$model"
fi

go run github.com/openconfig/ygot/generator \
  -structs_split_files_count=50 \
  -exclude_state \
  -generate_append \
  -generate_getters \
  -generate_simple_unions \
  -generate_populate_defaults \
  -output_dir=./${alt_version_name} \
  -package_name=nxos \
  "$model"

sed="$(command -v sed)"
if [[ "$(uname -s)" == 'Darwin' ]]; then
  sed="$(command -v gsed)"
  if ! [[ -x "$sed" ]]; then
    echo "Error: gsed is not installed. Please install it, e.g. via \`brew install gnu-sed\`." >&2
    exit 1
  fi
fi

# NOTE: The generated code contains a local path in the header which we replace.
find ./$alt_version_name -type f  -name '*.go' -exec "$sed" -i "s/This package was generated by.*/This package was generated by github.com\/openconfig\/ygot/g" \{\} \;

go install golang.org/x/tools/cmd/goimports@latest
goimports -w -local=github.wdf.sap.corp/cc/network-fabric-operator .
