// Code generated by "stringer -type=DistributionProtocol"; DO NOT EDIT.

package ospf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DistributionProtocolDirect-1]
	_ = x[DistributionProtocolStatic-2]
}

const _DistributionProtocol_name = "DistributionProtocolDirectDistributionProtocolStatic"

var _DistributionProtocol_index = [...]uint8{0, 26, 52}

func (i DistributionProtocol) String() string {
	i -= 1
	if i < 0 || i >= DistributionProtocol(len(_DistributionProtocol_index)-1) {
		return "DistributionProtocol(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DistributionProtocol_name[_DistributionProtocol_index[i]:_DistributionProtocol_index[i+1]]
}
